#!/usr/bin/env node

'use strict';

/* Sets version of package*.json files.
   Usage: node ./setversion */

const fs = require('fs');
const updater = require('jsonfile-updater');
const logger = require('./server/logger');

const version = process.argv[2];
process.title = 'setversion';

const replaceInFile = (filename, regexp, replacement) => {
  const contents = fs.readFileSync(filename, 'utf8');
  const result = contents.replace(regexp, replacement);
  fs.writeFileSync(filename, result, 'utf8');
};

const main = async () => {
  logger.info(`Setting version to ${version}.`);
  await updater('package.json').set('version', version);
  await updater('package-lock.json').set('version', version);
  await updater('ui/package.json').set('version', version);
  await updater('ui/package-lock.json').set('version', version);
  replaceInFile(
    'ui/src/App/__snapshots__/About.test.js.snap',
    /^(\s*)Verze:(\s*)\n(\s*)\S+(\s*)$/m,
    `$1Verze:$2\n$3${version}$4`
  );
};

main()
  .then()
  .catch(err => logger.error(err));
