#!/usr/bin/env node

'use strict';

const { execSync } = require('child_process');

/* Sets version of package*.json files. Then commits 5 files and adds a git tag.
   Usage: node ./setversion */

const fs = require('fs');
// eslint-disable-next-line import/no-extraneous-dependencies
const updater = require('jsonfile-updater');
const logger = require('./server/logger');

const version = process.argv[2];
process.title = 'setversion';

const replaceInFile = (filename, regexp, replacement) => {
  const contents = fs.readFileSync(filename, 'utf8');
  const result = contents.replace(regexp, replacement);
  fs.writeFileSync(filename, result, 'utf8');
};

const jsonFiles = ['package.json', 'package-lock.json', 'ui/package.json', 'ui/package-lock.json'];
const snapFiles = ['ui/src/App/__snapshots__/About.test.js.snap'];

const main = async () => {
  logger.info(`Setting version to ${version}.`);

  await Promise.all(jsonFiles.map(jsonFile => updater(jsonFile).set('version', version)));
  snapFiles.forEach(file =>
    replaceInFile(file, /^(\s*)Verze:(\s*)\n(\s*)\S+(\s*)$/m, `$1Verze:$2\n$3${version}$4`)
  );

  execSync(
    `git commit -m "Bump version number to ${version}." -- ${jsonFiles.join(' ')} ${snapFiles.join(
      ' '
    )}`
  );
  execSync(`git tag ${version}`);
};

main()
  .then()
  .catch(err => logger.error(err));
