#!/usr/bin/env node

'use strict';

const { execSync } = require('child_process');

/* Sets version of package*.json files. Then commits 6 files and adds a git tag.
   Usage: node ./setversion */

const fs = require('fs');
// eslint-disable-next-line import/no-extraneous-dependencies
const updater = require('jsonfile-updater');
const logger = require('./server/logger');

const version = process.argv[2];
process.title = 'setversion';

const replaceInFile = (filename, regexp, replacement) => {
  const contents = fs.readFileSync(filename, 'utf8');
  const result = contents.replace(regexp, replacement);
  fs.writeFileSync(filename, result, 'utf8');
};

const appFiles = ['ui/mobile/app.json'];
const jsonFiles = [
  'package.json',
  'package-lock.json',
  'ui/web/package.json',
  'ui/web/package-lock.json'
];
const snapFiles = ['ui/web/src/App/__snapshots__/About.test.jsx.snap'];

const main = async () => {
  logger.info(`Setting version to ${version}.`);

  await Promise.all(jsonFiles.map(jsonFile => updater(jsonFile).set('version', version)));
  await Promise.all(appFiles.map(appFile => updater(appFile).set('expo.version', version)));
  snapFiles.forEach(file =>
    replaceInFile(file, /^(\s*)Verze:(\s*)\n(\s*)\S+(\s*)$/m, `$1Verze:$2\n$3${version}$4`)
  );

  execSync(
    `git commit -m "Bump version number to ${version}." -- ${appFiles.join(' ')} ${jsonFiles.join(
      ' '
    )} ${snapFiles.join(' ')}`
  );
  execSync(`git tag ${version}`);
};

main()
  .then()
  .catch(err => logger.error(err));
